language: python

python:
  - 3.5
  - 3.6

before_install:
  pip install pip --upgrade;
  pip install -r requirements.txt;

install:
  - python setup.py install

script:
  python -m pytest --pyargs altair
